FROM python:3.9-slim

ENV DEBIAN_FRONTEND noninteractive 
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 

WORKDIR /app
COPY poetry.lock pyproject.toml ./
RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-dev

COPY . ./

CMD ["python", "main.py"]